#pragma once
#include "CompVision.h"

class MOG2 :
	public CompVision
{
public:
	MOG2();
	~MOG2();
	void ApplyFilter(Mat frame);
	Mat im_fgMaskMOG2;				     //fg mask generated by MOG2 method
	Ptr<BackgroundSubtractorMOG2> pMOG2; //MOG2 Background subtractor
};

